const ADD_POST = 'ADD_POST';
const ADD_COMMENT = 'ADD_COMMENT';
const DELETE_POST = 'DELETE_POST';
const DELETE_COMMENT = 'DELETE_COMMENT';
const VIEW_POST = 'VIEW_POST';
const UPDATE_POST = 'UPDATE_POST';
